### ISSUE TITLE
Developer docs tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy-website#366]
- [x] A Quick Start Guide to Building ZAP
- [ ] Building ZAP with Eclipse - #365
- [ ] Building ZAP with Intellij - Akshath
- [ ] Building ZAP with VSCode - Simon
- [ ] Building ZAP with ??? - Can add as many as we like/need
- [ ] Creating a new add-on in zap-extensions
- [ ] Creating a new add-on in a new repo
- [ ] Contributing code back to ZAP

**Comment by psiinon** [comment]
Feel free to add / suggest more and to volunteer to write any of these docs :D

**Comment by psiinon** [comment]
Note for self - vscode cwd can be configured as per https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

**Comment by kingthorin** [comment]
If we can get VSC sorted we can probably also get Code Spaces setup.
